### ISSUE TITLE
unexpected drift on boxes_6dof bag 

### ISSUE THREAD

**Issue by Sean0120** [robin-shaun/event-slam-accumulator-settings#1]
Hi, 
When I run the code on the bag boxes_6dof mentioned in your paper, the result is quite bad, as shown in the following image.
![result](https://user-images.githubusercontent.com/32014802/148024890-3204b9e3-4c0e-4dbe-8316-a4af8eb79c97.png)
Is this the problem of the configuration? If so, could you provide the config you used?

Thanks a lot.

**Comment by robin-shaun** [comment]
Does dynamic_6dof.bag work well?

**Comment by Sean0120** [comment]
Yes, this bag works well.
And here is the error plot.
[translation_error_posyaw_-1.pdf](https://github.com/robin-shaun/event-slam-accumulator-settings/files/7806102/translation_error_posyaw_-1.pdf)

**Comment by robin-shaun** [comment]
Remove this` if(inputImageCnt % 2 == 0)` in estimator.cpp, this will double the processing rate

**Comment by Sean0120** [comment]
Thanks for your help. It works much better.
And sorry for another question. Which number do you use in the rpg_trajectory_evaluation toolbox to get the Mean Position
Error you shown in the paper? I am a bit confused about how to get this metric in this toolbox.

![new_result](https://user-images.githubusercontent.com/32014802/148033670-effa7cd3-67c5-4399-8427-c402c383e752.png)

**Comment by robin-shaun** [comment]
I update readme which will help you.

**Comment by Sean0120** [comment]
I am sorry that there are several metrics in the toolbox, like the relative error and absolute error and I have no idea about which one should I print. Could you specify a bit more about which variable you used?

Thanks a lot.

**Comment by robin-shaun** [comment]
I have written this in readme.
https://github.com/robin-shaun/event-slam-accumulator-settings#6-evalute-results

**Comment by Sean0120** [comment]
Thanks for your help.
I am sorry that I didn't notice that you have uploaded the modified evaluation toolbox

**Comment by robin-shaun** [comment]
Max feature number in feature tracking in VINS-Fusion should be adjusted according to the scene. I will add this to paper later.

**Comment by robin-shaun** [comment]
Processing frequency of VINS-Fusion is also important and I have updated readme about it.
